name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint backend (flake8)
        working-directory: backend
        run: |
          pip install flake8 || true
          flake8 || true

      - name: Build frontend
        working-directory: frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: |
          npm ci
          npm run build

      - name: Docker Compose build (smoke)
        run: |
          docker compose -f docker-compose.yml build --no-cache
        env:
          # allow builds to use secrets if configured in organization/workflow
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  # NOTE: publishing images to a registry requires repo secrets (DOCKERHUB, GHCR, etc.)
