name: Build and Publish

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: ${{ secrets.GHCR_TOKEN }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: ${{ secrets.GHCR_TOKEN != '' }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/os_promptados-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: ${{ secrets.GHCR_TOKEN != '' }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/os_promptados-frontend:latest

      - name: Docker Compose smoke build
        run: docker compose -f docker-compose.yml build --no-cache

  # Note: pushing to DockerHub or GHCR requires secrets to be configured in repo settings.
